### ISSUE TITLE
`devspace ui` command intermittently fails with segmentation violation

### ISSUE THREAD

**Issue by wayspurrchen** [devspace-sh/devspace#1510]
**What happened?**

While running `devspace ui` I experienced a segmentation violation, which I have seen occur intermittently:

```
➜  repo git:(devspace-tweaks) devspace ui
[info]   Using namespace 'way'
[info]   Using kube context 'gke_lively-video_us-central1-b_lively-devspace-usc1b'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x569497f]

goroutine 1 [running]:
github.com/loft-sh/devspace/cmd.(*UICmd).RunUI(0xc000404040, 0x5fc4328, 0x7458330, 0x7458330, 0x0, 0x0, 0xc0010e0840, 0x7458330, 0x0, 0x0, ...)
        /Users/runner/work/devspace/devspace/cmd/ui.go:173 +0x4bf
github.com/loft-sh/devspace/cmd.NewUICmd.func1(0xc0010e0840, 0x7458330, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/work/devspace/devspace/cmd/ui.go:55 +0x89
github.com/spf13/cobra.(*Command).execute(0xc0010e0840, 0x7458330, 0x0, 0x0, 0xc0010e0840, 0x7458330)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000156840, 0x7458330, 0xc000156840, 0x0)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:895
github.com/loft-sh/devspace/cmd.Execute()
        /Users/runner/work/devspace/devspace/cmd/root.go:110 +0x7d
main.main()
        /Users/runner/work/devspace/devspace/main.go:20 +0xf7
```

**What did you expect to happen instead?**

`devspace ui` to work and launch the UI.

**How can we reproduce the bug?** (as minimally and precisely as possible)

I'm honestly not sure how to reproduce this issue, but running `devspace ui` I run into this fairly frequently and it appears to remain consistent until some state changes (not sure what) and the command works again.

**Local Environment:**

* DevSpace Version: 5.14.4
* Operating System: mac
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: google
* Kubernetes Version: 1.19

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@wayspurrchen thanks a lot for creating this issue! Yes seems like the panic occurs as soon as you call `devspace ui` and no `devspace.yaml` can be found. We'll fix this for the next release.

**Comment by deniseschannon** [comment]
Closing due to inactivity. DevSpace is on 6.3.12. If this is still an issue on the latest version, please open a new issue.
