### ISSUE TITLE
Exception in thread "main" java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by a5a5a9** [devspace-sh/devspace#1582]
**What happened?**
hot reloading not working in the devspace-quickstart-java example

Exception in thread "main" java.net.BindException: Address already in use
at java.base/sun.nio.ch.Net.bind0(Native Method)
at java.base/sun.nio.ch.Net.bind(Net.java:552)
at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:336)
at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:101)
at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)

**What did you expect to happen instead?**
After a change in the QuickStart.java  the hotreload triggers but it fails to launch the app thru the java -jar command.

**How can we reproduce the bug?** (as minimally and precisely as possible)
run the devspace-quickstart-java example , make a change in the Quickstart.java code and the launch will fail  with:

Exception in thread "main" java.net.BindException: Address already in use

**Local Environment:**

* DevSpace Version: \[use `devspace --version`\]
* Operating System: linux
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: aws
* Kubernetes Version: 1.21

/kind bug

**Comment by FabianKramm** [comment]
@a5a5a9 thanks for creating this issue! We'll take a look and will fix the problem

**Comment by zerbitx** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
