### ISSUE TITLE
DevSpaces Crashes when running devspaces-init and asking to use customer Container Registry

### ISSUE THREAD

**Issue by tshaiman** [devspace-sh/devspace#2823]
**What happened?**  
while running `devspace init` wizzard I selected "Use Other Registry" when Asked which registry to use to push images .
error : 
```
panic: regexp: Compile(`^(?!-)[a-z0-9-]{1,63}(\.[a-z0-9-]{1,63})*$`): error parsing regexp: invalid or unsupported Perl syntax: `(?!`

goroutine 1 [running]:
regexp.MustCompile({0x2da7757, 0x2a})
        /Users/runner/hostedtoolcache/go/1.20.13/x64/src/regexp/regexp.go:319 +0xbb
github.com/loft-sh/devspace/pkg/util/survey.(*survey).Question(0x0?, 0xc0002503f0)
        /Users/runner/work/devspace/devspace/pkg/util/survey/survey.go:45 +0x4d
github.com/loft-sh/devspace/pkg/util/log.(*StreamLogger).Question(0xc000193700, 0xc0002503f0)
        /Users/runner/work/devspace/devspace/pkg/util/log/stream_logger.go:537 +0x1ba
github.com/loft-sh/devspace/pkg/devspace/configure.(*manager).AddImage(0xc000846dc0, {0x2d4eae0, 0x3}, {0x0, 0x0}, {0xc0006081e0, 0x22}, {0x2d5c124, 0xc})
        /Users/runner/work/devspace/devspace/pkg/devspace/configure/image.go:174 +0xebd
github.com/loft-sh/devspace/cmd.(*InitCmd).initDevspace(0xc00030f5e0, {0x311f958, 0x4a5d108}, {0x3119ac0, 0xc000551ac0})
        /Users/runner/work/devspace/devspace/cmd/init.go:424 +0x1964
github.com/loft-sh/devspace/cmd.(*InitCmd).Run(0xc00030f5e0, {0x311f958, 0x4a5d108})
        /Users/runner/work/devspace/devspace/cmd/init.go:162 +0x3a5
github.com/loft-sh/devspace/cmd.NewInitCmd.func1(0xc0008a1200?, {0x4a5d108?, 0x0?, 0x0?})
        /Users/runner/work/devspace/devspace/cmd/init.go:94 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc0008a1200, {0x4a5d108, 0x0, 0x0})
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004f00)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:968
github.com/loft-sh/devspace/cmd.Execute()
        /Users/runner/work/devspace/devspace/cmd/root.go:151 +0x1af
main.main()
        /Users/runner/work/devspace/devspace/main.go:17 +0x2c
```

**What did you expect to happen instead?**  
- wizard should run to completion

**How can we reproduce the bug?** (as minimally and precisely as possible)  
- install DevSpaces on Windows
- run the quick start tutorial 
- 
My devspace.yaml:
```
version: ...
...
```

**Local Environment:**  
- DevSpace Version:  6.3.12
- Operating System: windows 
- ARCH of the OS: AMD64 
**Kubernetes Cluster:**  
( none relevnat we haven't reached this step yet) 
**Anything else we need to know?**

**Comment by djberube** [comment]
I can confirm I'm seeing the same thing. I was able to work around by selecting DockerHub and then changing the image name in devspace.yaml to reflect the custom registry.

**Comment by nethi** [comment]
I still see the issue with latest version 6.3.12
